document.write('<table id="tubiaotb"  style="margin-top:20px; margin-bottom:20px;">');
document.write('<tr><td rowspan="2">');
document.write('<a href="/contact.aspx"><img src="/images/zhxm52.jpg" alt="" border="0" /></a></td>');

document.write('<td>');
document.write('<a href="/gas_industry.htm"><img src="/images/工业图标.jpg" alt="" border="0" /></a><br>');
document.write('<a href="/gas_industry.htm">氧气 氮气 氩气</a><br>');
document.write('<a href="/gas_industry.htm">二氧化碳 乙炔</a><br>');
document.write('<a href="/gas_industry.htm">工业氦 氢气 更多...</a><br>');
document.write('</td>');
document.write('<td>');
document.write('<a href="/gas_high_purity.htm"><img src="/images/高纯图标.jpg" alt="" border="0" /></a><br>');
document.write('<a href="/gas_high_purity.htm">高纯氧 高纯氦 高纯氮</a><br>');
document.write('<a href="/gas_high_purity.htm">高纯氩 高纯稀有气体</a><br>');
document.write('<a href="/gas_high_purity.htm">高纯氢气 更多...</a><br>');
document.write('</td>');
document.write('<td>');
document.write('<a href="/gas_standard.htm"><img src="/images/标准图标.jpg" alt="" border="0" /></a><br>');
document.write('<a href="/gas_standard.htm">空分用标准气</a><br>');
document.write('<a href="/gas_standard.htm">石油化工用标准气</a><br>');
document.write('<a href="/gas_standard.htm">更多...</a><br>');
document.write('</td>');
document.write('<td>');
document.write('<a href="/gas_liquid.htm"><img src="/images/液态图标.jpg" alt="" border="0" /></a><br>');
document.write('<a href="/gas_liquid.htm">液氮 液氩 液氧</a><br>');
document.write('<a href="/gas_liquid.htm">液态二氧化碳</a><br>');
document.write('<a href="/gas_liquid.htm">液氦 更多...</a><br>');
document.write('</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td>');
document.write('<a href="/gas_Medical.htm"><img src="/images/医疗图标.jpg" alt="" border="0" /></a><br>');
document.write('<a href="/gas_Medical.htm">医用氧 氮气 笑气</a><br>');
document.write('<a href="/gas_Medical.htm">一氧化氮 二氧化碳 </a><br>');
document.write('<a href="/gas_Medical.htm">氢气 更多...</a><br>');
document.write('</td>');
document.write('<td>');
document.write('<a href="/gas_electron.htm"><img src="/images/电子图标.jpg" alt="" border="0" /></a><br>');
document.write('<a href="/gas_electron.htm">氖气、氪气、氙气</a><br>');
document.write('<a href="/gas_electron.htm">一氧化二氮 氨气</a><br>');
document.write('<a href="/gas_electron.htm">超纯气 更多...</a><br>');
document.write('</td><td>');
document.write('<a href="/gas_mixed.htm"><img src="/images/混合图标.jpg" alt="" border="0" /></a><br>');
document.write('<a href="/gas_mixed.htm">焊接混合气</a><br>');
document.write('<a href="/gas_mixed.htm">消防混合气</a><br>');
document.write('<a href="/gas_mixed.htm">空气 更多...</a><br>');
document.write('</td><td>');
document.write('<a href="/gas_high_purity.htm"><img src="/images/食品图标.jpg" alt="" border="0" /></a><br>');
document.write('<a href="/gas_high_purity.htm">食品级二氧化碳</a><br>');
document.write('<a href="/gas_high_purity.htm">氮气 </a><br>');
document.write('<a href="/gas_high_purity.htm">更多...</a><br>');
document.write('</td>');
document.write('</tr>');
document.write('</table>');